### Create a new product
POST http://localhost:5000/api/v1/products
Content-Type: application/json

{
  "name": "Organic apple/mangoes",
  "description": "Fresh from the farm.",
  "price": 99.99,
  "stock": 50,
  "imageUrl": "https://example.com/mango.jpg",
  "category": "fruits"
}

### Get all products
GET http://localhost:5000/api/v1/products

### Get a single product by ID (Replace {id} with an actual product ID)
GET http://localhost:5000/api/v1/products/60044643-d03b-4b94-8509-0d1b79af83f4

### Update a product (Replace {id} with an actual product ID)
PUT http://localhost:5000/api/v1/products/60044643-d03b-4b94-8509-0d1b79af83f4
Content-Type: application/json

{
  "price": 89.99,
  "stock": 40
}

### Delete a product (Replace {id} with an actual product ID)
DELETE http://localhost:5000/api/v1/products/{id}

